#include "stdafx.h"
#include <dinput.h>
#include "key_binding_registrator.h"
#include "xr_level_controller.h"

using namespace luabind;

int dik_to_bind(int dik){
	return get_binded_action(dik);
}

#pragma optimize("s",on)
void key_binding_registrator::script_register(lua_State *L)
{
	module(L)
	[
		def("dik_to_bind",		&dik_to_bind),

		class_<enum_exporter<EGameActions> >("key_bindings")
			.enum_("commands")
			[
				value("kFWD",						int(kFWD)),
				value("kBACK",						int(kBACK)),
				value("kL_STRAFE",					int(kL_STRAFE)),
				value("kR_STRAFE",					int(kR_STRAFE)),
				value("kL_LOOKOUT",					int(kL_LOOKOUT)),
				value("kR_LOOKOUT",					int(kR_LOOKOUT)),
				value("kLEFT",						int(kLEFT)),
				value("kRIGHT",						int(kRIGHT)),
				value("kUP",						int(kUP)),
				value("kDOWN",						int(kDOWN)),
				value("kJUMP",						int(kJUMP)),
				value("kCROUCH",					int(kCROUCH)),
				value("kCROUCH_TOGGLE",				int(kCROUCH_TOGGLE)),
				value("kACCEL",						int(kACCEL)),
				value("kCAM_1",						int(kCAM_1)),
				value("kCAM_2",						int(kCAM_2)),
				value("kCAM_3",						int(kCAM_3)),
				value("kCAM_4",						int(kCAM_4)),
				value("kCAM_ZOOM_IN",				int(kCAM_ZOOM_IN)),
				value("kCAM_ZOOM_OUT",				int(kCAM_ZOOM_OUT)),
				value("kTORCH",						int(kTORCH)),
				value("kNIGHT_VISION",				int(kNIGHT_VISION)),
				value("kWPN_1",						int(kWPN_1)),
				value("kWPN_2",						int(kWPN_2)),
				value("kWPN_3",						int(kWPN_3)),
				value("kWPN_4",						int(kWPN_4)),
				value("kWPN_5",						int(kWPN_5)),
				value("kWPN_6",						int(kWPN_6)),
				value("kWPN_NEXT",					int(kWPN_NEXT)),
//.				value("kWPN_PREV",					int(kWPN_PREV)),
				value("kWPN_FIRE",					int(kWPN_FIRE)),
				value("kWPN_RELOAD",				int(kWPN_RELOAD)),
				value("kWPN_ZOOM",					int(kWPN_ZOOM)),
				value("kWPN_FUNC",					int(kWPN_FUNC)),
				value("kUSE",						int(kUSE)),
				value("kDROP",						int(kDROP)),
				value("kSCORES",					int(kSCORES)),
				value("kCHAT",						int(kCHAT)),
				value("kSCREENSHOT",				int(kSCREENSHOT)),
				value("kQUIT",						int(kQUIT)),
				value("kCONSOLE",					int(kCONSOLE)),
				value("kINVENTORY",					int(kINVENTORY)),
				value("kBUY",						int(kBUY)),
				value("kSKIN",						int(kSKIN)),
				value("kTEAM",						int(kTEAM))
			],
		class_< key_binding_registrator>("Keys")
		.enum_("Keys")
		[
			value("Key_A", SDL_SCANCODE_A),
			value("Key_B", SDL_SCANCODE_B),
			value("Key_C", SDL_SCANCODE_C),
			value("Key_D", SDL_SCANCODE_D),
			value("Key_E", SDL_SCANCODE_E),
			value("Key_F", SDL_SCANCODE_F),
			value("Key_G", SDL_SCANCODE_G),
			value("Key_H", SDL_SCANCODE_H),
			value("Key_I", SDL_SCANCODE_I),
			value("Key_J", SDL_SCANCODE_J),
			value("Key_K", SDL_SCANCODE_K),
			value("Key_L", SDL_SCANCODE_L),
			value("Key_M", SDL_SCANCODE_M),
			value("Key_N", SDL_SCANCODE_N),
			value("Key_O", SDL_SCANCODE_O),
			value("Key_P", SDL_SCANCODE_P),
			value("Key_Q", SDL_SCANCODE_Q),
			value("Key_R", SDL_SCANCODE_R),
			value("Key_S", SDL_SCANCODE_S),
			value("Key_T", SDL_SCANCODE_T),
			value("Key_U", SDL_SCANCODE_U),
			value("Key_V", SDL_SCANCODE_V),
			value("Key_W", SDL_SCANCODE_W),
			value("Key_X", SDL_SCANCODE_X),
			value("Key_Y", SDL_SCANCODE_Y),
			value("Key_Z", SDL_SCANCODE_Z),
			
			value("Key_1", SDL_SCANCODE_1),
			value("Key_2", SDL_SCANCODE_2),
			value("Key_3", SDL_SCANCODE_3),
			value("Key_4", SDL_SCANCODE_4),
			value("Key_5", SDL_SCANCODE_5),
			value("Key_6", SDL_SCANCODE_6),
			value("Key_7", SDL_SCANCODE_7),
			value("Key_8", SDL_SCANCODE_8),
			value("Key_9", SDL_SCANCODE_9),
			value("Key_0", SDL_SCANCODE_0),

			value("Key_Return", SDL_SCANCODE_RETURN),
			value("Key_Escape", SDL_SCANCODE_ESCAPE),
			value("Key_Backspace", SDL_SCANCODE_BACKSPACE),
			value("Key_Tab", SDL_SCANCODE_TAB),
			value("Key_Space", SDL_SCANCODE_SPACE),
			
			value("Key_Minus", SDL_SCANCODE_MINUS),
			value("Key_Equals", SDL_SCANCODE_EQUALS),
			value("Key_Leftbracket", SDL_SCANCODE_LEFTBRACKET),
			value("Key_Rightbracket", SDL_SCANCODE_RIGHTBRACKET),
			value("Key_Backslash", SDL_SCANCODE_BACKSLASH),
//			value("Key_Nonushash", SDL_SCANCODE_NONUSHASH),
            value("Key_Semicolon", SDL_SCANCODE_SEMICOLON),
			value("Key_Apostrophe", SDL_SCANCODE_APOSTROPHE),
			value("Key_Grave", SDL_SCANCODE_GRAVE),
			value("Key_Comma", SDL_SCANCODE_COMMA),
			value("Key_Period", SDL_SCANCODE_PERIOD),
			value("Key_Slash", SDL_SCANCODE_SLASH),
//			value("Key_Capslock", SDL_SCANCODE_CAPSLOCK),

            value("Key_F1", SDL_SCANCODE_F1),
			value("Key_F2", SDL_SCANCODE_F2),
			value("Key_F3", SDL_SCANCODE_F3),
			value("Key_F4", SDL_SCANCODE_F4),
			value("Key_F5", SDL_SCANCODE_F5),
			value("Key_F6", SDL_SCANCODE_F6),
			value("Key_F7", SDL_SCANCODE_F7),
			value("Key_F8", SDL_SCANCODE_F8),
			value("Key_F9", SDL_SCANCODE_F9),
			value("Key_F10", SDL_SCANCODE_F10),
			value("Key_F11", SDL_SCANCODE_F11),
			value("Key_F12", SDL_SCANCODE_F12),

			value("Key_PrintScreen", SDL_SCANCODE_PRINTSCREEN),
			value("Key_ScrollLock", SDL_SCANCODE_SCROLLLOCK),
			value("Key_Pause", SDL_SCANCODE_PAUSE),
			value("Key_Insert", SDL_SCANCODE_INSERT),
			value("Key_Home", SDL_SCANCODE_HOME),
			value("Key_PageUp", SDL_SCANCODE_PAGEUP),
			value("Key_Delete", SDL_SCANCODE_DELETE),
			value("Key_End", SDL_SCANCODE_END),
			value("Key_PageDown", SDL_SCANCODE_PAGEDOWN),
			value("Key_Right", SDL_SCANCODE_RIGHT),
			value("Key_Left", SDL_SCANCODE_LEFT),
			value("Key_Down", SDL_SCANCODE_DOWN),
			value("Key_Up", SDL_SCANCODE_UP),

			value("Key_NumLock", SDL_SCANCODE_NUMLOCKCLEAR),
			value("Key_KP_Divide", SDL_SCANCODE_KP_DIVIDE),
			value("Key_KP_Multiply", SDL_SCANCODE_KP_MULTIPLY),
			value("Key_KP_Minus", SDL_SCANCODE_KP_MINUS),
			value("Key_KP_Plus", SDL_SCANCODE_KP_PLUS),
			value("Key_KP_Enter", SDL_SCANCODE_KP_ENTER),
			value("Key_KP_1", SDL_SCANCODE_KP_1),
			value("Key_KP_2", SDL_SCANCODE_KP_2),
			value("Key_KP_3", SDL_SCANCODE_KP_3),
			value("Key_KP_4", SDL_SCANCODE_KP_4),
			value("Key_KP_5", SDL_SCANCODE_KP_5),
			value("Key_KP_6", SDL_SCANCODE_KP_6),
			value("Key_KP_7", SDL_SCANCODE_KP_7),
			value("Key_KP_8", SDL_SCANCODE_KP_8),
			value("Key_KP_9", SDL_SCANCODE_KP_9),
			value("Key_KP_0", SDL_SCANCODE_KP_0),
			value("Key_KP_Period", SDL_SCANCODE_KP_PERIOD),

			value("Key_Application", SDL_SCANCODE_APPLICATION),

			value("Key_KP_Equals", SDL_SCANCODE_KP_EQUALS),
			value("Key_F13", SDL_SCANCODE_F13),
			value("Key_F14", SDL_SCANCODE_F14),
			value("Key_F15", SDL_SCANCODE_F15),
			value("Key_F16", SDL_SCANCODE_F16),
			value("Key_KP_Comma", SDL_SCANCODE_KP_COMMA),

			value("Key_LCTRL", SDL_SCANCODE_LCTRL),
			value("Key_LShift", SDL_SCANCODE_LSHIFT),
			value("Key_LAlt", SDL_SCANCODE_LALT),
			value("Key_LGui", SDL_SCANCODE_LGUI),
			value("Key_RCTRL", SDL_SCANCODE_RCTRL),
			value("Key_RShift", SDL_SCANCODE_RSHIFT),
			value("Key_RAlt", SDL_SCANCODE_RALT),
			value("Key_RGui", SDL_SCANCODE_RGUI),

			value("LMB", MOUSE_LEFT_BUTTON_IDX),
			value("MMB", MOUSE_MIDDLE_BUTTON_IDX),
			value("RMB", MOUSE_RIGHT_BUTTON_IDX),
			value("X1_mouse_button", MOUSE_BACK_BUTTON_IDX),
			value("X2_mouse_button", MOUSE_FORWARD_BUTTON_IDX)
		]
	];
}
