#pragma once

#include <SDL3/SDL_scancode.h>

enum
{
	MOUSE_LEFT_BUTTON = 0,
	MOUSE_MIDDLE_BUTTON,
	MOUSE_RIGHT_BUTTON,
	MOUSE_BACK_BUTTON,
	MOUSE_FORWARD_BUTTON,

	MOUSE_LEFT_BUTTON_IDX = 291,
	MOUSE_MIDDLE_BUTTON_IDX,
	MOUSE_RIGHT_BUTTON_IDX,
	MOUSE_BACK_BUTTON_IDX,
	MOUSE_FORWARD_BUTTON_IDX,
};